resolver: lts-18.0

ghc-options:
  $targets: -O2
    -Wall
    -Wcompat
    -Werror
    -Wmissing-deriving-strategies
    -Wwarn=name-shadowing
    -rtsopts
    -threaded
    -with-rtsopts=-N

packages:
  - .

extra-deps:
  - docker-0.6.0.5@sha256:8dbffa649e19880b0ecbe9fc28dfc0e8e2b03e5e810a804f388006317f240646,4044

allow-newer: true

extra-include-dirs:
  - ~/.nix-profile/include

nix:
  enable: true
  add-gc-roots: true
  pure: false
  shell-file: stack.nix
